// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppTheme } from "./AppTheme";
import type { GlobalDefaultOptions } from "./GlobalDefaultOptions";
import type { SkipSaveType } from "./SkipSaveType";

export type AppOptions = { skipSaveType: SkipSaveType, skipSaveMinRatio: number, newFileNameSuffix: string, globalDefaultOptions: Array<GlobalDefaultOptions>, appTheme: AppTheme, confirmOnClose: boolean, };
