// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageFormat } from "./ImageFormat";

export type GlobalDefaultOptions = { 
/**
 * Concrete input formats this profile applies to.
 * An empty list means "all formats".
 */
inputFormats: Array<ImageFormat>, 
/**
 * Output format, or `None` to keep the input format.
 */
outputFormat: ImageFormat | null, 
/**
 * The nested optimize options are owned by the shared crate and already
 * exposed to the frontend as `OptimizeOptions` from `@imgo/shared-js`.
 */
options: import("@imgo/shared-js").OptimizeOptions, };
