// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageObject } from "./ImageObject";
import type { ImageResolution } from "./ImageResolution";

export type ImageOptimizeResult = { inputResolution: ImageResolution, image: ImageObject, };
