// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileObject } from "./FileObject";
import type { ImageFormat } from "./ImageFormat";
import type { ImageResolution } from "./ImageResolution";

export type ImageObject = { 
/**
 * 文件
 */
file: FileObject, 
/**
 * 格式
 */
format: ImageFormat, 
/**
 * 分辨率
 */
resolution: ImageResolution | null, };
