// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageFormat = "PNG" | "JPEG" | "GIF" | "WEBP" | "PNM" | "TIFF" | "TGA" | "DDS" | "BMP" | "ICO" | "HDR" | "OPENEXR" | "FARBFELD" | "AVIF" | "QOI" | "HEIC" | "JXL";
