// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveFilesTriggerType = "SAVE_AS" | "AUTO_NEW_NAME" | "OVERRIDE" | "SAVE_TO_DIR";
